name: mineros-cli-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  cli-test:
    if: github.repository == 'loganpowell/MinerOS'
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: install & test
        run: |
          uv venv --python 3.12
          source .venv/bin/activate
          uv pip install ".[test]"
          cd $GITHUB_WORKSPACE && python tests/clean_coverage.py
          cd $GITHUB_WORKSPACE && coverage run
          cd $GITHUB_WORKSPACE && python tests/get_coverage.py
